data_types = {
    "clee": "str",
    "id": "int",
    "nombre": "str",
    "razon_social": "str",
    "clase_actividad": "str",
    "estrato": "str",
    "tipo_vialidad": "str",
    "calle": "str",
    "num_exterior": "int",
    "num_interior": "str",
    "colonia": "str",
    "cp": "int",
    "ubicacion": "str",
    "telefono": "int",
    "correo_e": "str",
    "sitio_internet": "str",
    "tipo": "str",
    "longitud": "float",
    "latitud": "float",
    "tipo_corredor_industrial": "str",
    "nom_corredor_industrial": "str",
    "numero_local": "str",
    "localidad": "str",
    "municipio": "str",
    "entidad": "str"
  }